name: Project Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: 3.11.2
      - name: Run tests
        run: |
          pipenv install --dev
          pipenv run pytest

